<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>vbsp</AssemblyName>
	<OutputPath>..\..\Output\bin</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\FileFormats\FileFormats.csproj" />
  </ItemGroup>

</Project>
