using System;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using System.Text;
using System.Threading.Tasks;

namespace FileFormats.MDL
{
    // MDL Flags
    // We map these to the bits that define them in the .MDL file (https://developer.valvesoftware.com/wiki/MDL).\
    [Flags]
    public enum MDLFlags
    {
        STUDIOHDR_FLAGS_AUTOGENERATED_HITBOX = 0x00000001,
        STUDIOHDR_FLAGS_USES_ENV_CUBEMAP = 0x00000002,
        STUDIOHDR_FLAGS_FORCE_OPAQUE = 0x00000004,
        STUDIOHDR_FLAGS_TRANSLUCENT_TWOPASS = 0x00000008,
        STUDIOHDR_FLAGS_STATIC_PROP = 0x00000010,
        STUDIOHDR_FLAGS_USES_FB_TEXTURE = 0x00000020,
        STUDIOHDR_FLAGS_HASSHADOWLOD = 0x00000040,
        STUDIOHDR_FLAGS_USES_BUMPMAPPING = 0x00000080,
        STUDIOHDR_FLAGS_USE_SHADOWLOD_MATERIALS = 0x00000100,
        STUDIOHDR_FLAGS_OBSOLETE = 0x00000200,
        STUDIOHDR_FLAGS_UNUSED = 0x00000400,
        STUDIOHDR_FLAGS_NO_FORCED_FADE = 0x00000800,
        STUDIOHDR_FLAGS_FORCE_PHONEME_CROSSFADE = 0x00001000,
        STUDIOHDR_FLAGS_CONSTANT_DIRECTIONAL_LIGHT_DOT = 0x00002000,
        STUDIOHDR_FLAGS_FLEXES_CONVERTED = 0x00004000,
        STUDIOHDR_FLAGS_BUILT_IN_PREVIEW_MODE = 0x00008000,
        STUDIOHDR_FLAGS_AMBIENT_BOOST = 0x00010000,
        STUDIOHDR_FLAGS_DO_NOT_CAST_SHADOWS = 0x00020000,
        STUDIOHDR_FLAGS_CAST_TEXTURE_SHADOWS = 0x00040000,
        STUDIOHDR_FLAGS_VERT_ANIM_FIXED_POINT_SCALE = 0x00200000
    }

    // MDL Header (studiohdr_t)
    public struct MDLHeader
    {
        public int ID; // FourCC (IDST)
        public int Version;
        public int Checksum;
        public string Name; // Name of model as defined in the file

        public int DataLength; // Data size of MDL file in bytes

        public Vector3 EyePosition; // Position of player viewpoint relative to model origin (????)
        public Vector3 IllumPosition; // Position of light source relative to model origin
        public Vector3 HullMin; // Corner of model hull box with the least X/Y/Z values
        public Vector3 HullMax; // Opposite corner of model hull box
        public Vector3 ViewBBMin; // Minimum bounding box of model
        public Vector3 ViewBBMax; // Maximum bounding box of model

        public MDLFlags Flags; // Flags for the model

        // OFFSETS
        // Offsets are from the start of the file

        // Bone Data
        public int BoneCount;
        public int BoneOffset;

        // Bone Controller Data
        public int BoneControllerCount;
        public int BoneControllerOffset;

        // Hitbox Data
        public int HitboxCount;
        public int HitboxOffset;

        // Animation Data
        public int LocalAnimCount;
        public int LocalAnimOffset;

        // Sequence Data
        public int LocalSequenceCount;
        public int LocalSequenceOffset;

        public int ActivityListVersion; // ??
        public int EventsIndexed; // ??

        // VMT Materials
        // Texture Data
        public int TextureCount;
        public int TextureOffset;

        public int TextureDirCount;
        public int TextureDirOffset;

        // Skins
        public int SkinReferenceCount;
        public int SkinFamilyCount;
        public int SkinReferenceIndex;

        // Body Parts
        public int BodyPartCount;
        public int BodyPartOffset;

        // Attatchment Points
        public int AttachmentCount;
        public int AttachmentOffset;

    }

    // 64 Bytes Long
    public struct MDLTexture
    {
        // Number of bytes past the beginning of this structure
        // where the first character of the texture name can be found
        public int NameOffset;
        public int Flags;

        public int Used; // Padding
        public int Unused; // Padding

        public int Material;
        public int ClientMaterial;

        public int[] unused2; // Final Padding
    }
}
